agents:
  queue: "agent-runners-windows-amd64"

steps:
  - label: ":bazel: Build"
    commands:
      - bazelisk build --config=microsoft_compiler_opts //...
      - bazelisk test --config=microsoft_compiler_opts //...
