agents:
  queue: "agent-runners-windows-amd64"

steps:
  - label: ":bazel: Build"
    commands:
      - bazelisk build --copt=/std:c++20 //...
  - label: ":bazel: Test"
    commands:
      - bazelisk test --copt=/std:c++20 //...
