name: ProjectCore

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ubuntu-latest-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - run: CC=gcc bazel test --copt=-std=c++20 //...

  ubuntu-latest-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Install clang
      run:   |
         sudo apt update
         sudo apt install clang
    - name: Testing...
      run: CC=clang bazel test --copt=-std=c++20 //...
