name: ProjectCore

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  windows-latest-msvc:
    runs-on: windows-latest
    steps:
    - name: Install MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Building...
      run: bazelisk build --copt=/std:c++20 //...
    - name: Testing...
      run: bazelisk test --copt=/std:c++20 //...

  windows-latest-gcc:
    runs-on: windows-latest
    steps:
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Building...
      run: bazelisk build --copt=-std=c++20 //...
    - name: Testing...
      run: bazelisk test --copt=-std=c++20 //..
      
  ubuntu-latest-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Version
      run: gcc --version
    - name: Building...
      run: CC=gcc bazelisk build --copt=-std=c++20 //...
    - name: Testing...
      run: CC=gcc bazelisk test --copt=-std=c++20 //...

  ubuntu-latest-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Install clang
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x ./llvm.sh
        sudo ./llvm.sh 17
    - name: Version
      run: clang --version
    - name: Building...
      run: CC=clang++-17 bazelisk build --copt=-std=c++20 //...
    - name: Testing...
      run: CC=clang++-17 bazelisk test --copt=-std=c++20 //...
